AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Partfinder - Machine part search engine
Parameters:
  ExecEnv:
    Type: String
    Default: dev
    AllowedValues:
      - local
      - dev
      - test
      - prod

Resources:
  PartfinderAdminWebsite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ExecEnv}.demo.partfinder.ai
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET

PartfinderDemoWebsitePolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref PartfinderDemoWebsite
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Join
              - /
              - - !GetAtt
                  - PartfinderDemoWebsite
                  - Arn
                - "*"
            Principal: "*"
    DependsOn:
      - PartfinderDemoWebsite

  # Cloudfront Distribution for Demo Website
  PartfinderDemoCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Partfinder Demo Website
        Origins:
          - DomainName:
              !Select
              - 1
              - !Split
                - "//"
                - !GetAtt PartfinderDemoWebsite.WebsiteURL
            Id: S3WebsiteOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30

        Enabled: "true"
        HttpVersion: "http2"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          TargetOriginId: S3WebsiteOrigin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          MaxTTL:
            !If [CreateDevResource, 0, !If [CreateTestResource, 3600, 604800]]
          MinTTL: !If [CreateDevResource, 0, 3600]
          DefaultTTL:
            !If [CreateDevResource, 0, !If [CreateTestResource, 3600, 86400]]
        PriceClass: PriceClass_All
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref AcmCertifcateArn
        #   SslSupportMethod: sni-only
      Tags:
        - Key: Name
          Value: Partfinder Demo Website
